version: 2

sources:
  - name: greenery
    schema: public
    database: dbt

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 72, period: hour}

    tables:
      - name: orders
        loaded_at_field: created_at

      - name: users
        loaded_at_field: created_at

      - name: events
        loaded_at_field: event_at

      - name: addresses

      - name: order_items

      - name: products

      - name: promos
