version: 2

sources:
  - name: greenery
    schema: public
    database: dbt

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 72, period: hour}

    tables:
      - name: orders
      - name: users
      - name: events
      - name: addresses
      - name: order_items
      - name: products
      - name: promos
